// Header: Stm32f103c8 Drivers
// File Name: RCC Source File
// Author: Omar Megahed Ismail
// Date: 2022/03/16
#include "RCC.h"
#include "Macros.h"
void vRCC_Init(void)
{

	/*CLK SOURCE*/
	switch (SYSTEM_CLK_SRC)
	{
		/*PLL CLK*/
	case PLL:
		/*SELECT PLL AS SYSTEM CLK*/
		CLEAR_BIT(RCC_CFGR, SW_0);
		SET_BIT(RCC_CFGR, SW_1);
		/*PLL CLK SOURCE*/
		switch (PLL_CLK_SRC)
		{
			/*PLL->HSE*/
		case HSE:
			/*PLL->HSE SOURCE*/
			switch (HSE_SRC)
			{
			case CRYSTAL:
				CLEAR_BIT(RCC_CR, HSEBYP);
				break; // CRYSTAL IS HSE SOURCE
			case RC:
				SET_BIT(RCC_CR, HSEBYP);
				break; // EXTERNAL RC IS HSE SOURCE
			default:
				CLEAR_BIT(RCC_CR, HSEBYP);
				break;
			}
			/*HSE PRESCALER*/
			switch (HSE_PRE)
			{
			case 1:
				CLEAR_BIT(RCC_CFGR, PLLXTPRE);
				break; // HSE CLK/1
			case 2:
				SET_BIT(RCC_CFGR, PLLXTPRE);
				break; // HSE CLK/2
			default:
				CLEAR_BIT(RCC_CFGR, PLLXTPRE);
				break;
			}

			SET_BIT(RCC_CR, HSEON);	   // HSE ON
			SET_BIT(RCC_CFGR, PLLSRC); // HSE IS PLL SOURCE
			break;
			/*PLL->HSI*/
		case HSI:
			SET_BIT(RCC_CR, HSION);		 // HIE ON
			CLEAR_BIT(RCC_CFGR, PLLSRC); // HSI IS PLL SOURCE
			break;

		default:
			SET_BIT(RCC_CR, HSION);		 // HIE ON
			CLEAR_BIT(RCC_CFGR, PLLSRC); // HSI IS PLL SOURCE
			break;
		}
		/*PLL MULTIPLICATION FACTOR*/
		switch (PLL_MULT)
		{
		case 2:
			CLEAR_BIT(RCC_CFGR, PLLMUL_3);
			CLEAR_BIT(RCC_CFGR, PLLMUL_2);
			CLEAR_BIT(RCC_CFGR, PLLMUL_1);
			CLEAR_BIT(RCC_CFGR, PLLMUL_0);
			break; // PLL MUL FACTOR *2
		case 3:
			CLEAR_BIT(RCC_CFGR, PLLMUL_3);
			CLEAR_BIT(RCC_CFGR, PLLMUL_2);
			CLEAR_BIT(RCC_CFGR, PLLMUL_1);
			SET_BIT(RCC_CFGR, PLLMUL_0);
			break; // PLL MUL FACTOR *3
		case 4:
			CLEAR_BIT(RCC_CFGR, PLLMUL_3);
			CLEAR_BIT(RCC_CFGR, PLLMUL_2);
			SET_BIT(RCC_CFGR, PLLMUL_1);
			CLEAR_BIT(RCC_CFGR, PLLMUL_0);
			break; // PLL MUL FACTOR *4
		case 5:
			CLEAR_BIT(RCC_CFGR, PLLMUL_3);
			CLEAR_BIT(RCC_CFGR, PLLMUL_2);
			SET_BIT(RCC_CFGR, PLLMUL_1);
			SET_BIT(RCC_CFGR, PLLMUL_0);
			break; // PLL MUL FACTOR *5
		case 6:
			CLEAR_BIT(RCC_CFGR, PLLMUL_3);
			SET_BIT(RCC_CFGR, PLLMUL_2);
			CLEAR_BIT(RCC_CFGR, PLLMUL_1);
			CLEAR_BIT(RCC_CFGR, PLLMUL_0);
			break; // PLL MUL FACTOR *6
		case 7:
			CLEAR_BIT(RCC_CFGR, PLLMUL_3);
			SET_BIT(RCC_CFGR, PLLMUL_2);
			CLEAR_BIT(RCC_CFGR, PLLMUL_1);
			SET_BIT(RCC_CFGR, PLLMUL_0);
			break; // PLL MUL FACTOR *7
		case 8:
			CLEAR_BIT(RCC_CFGR, PLLMUL_3);
			SET_BIT(RCC_CFGR, PLLMUL_2);
			SET_BIT(RCC_CFGR, PLLMUL_1);
			CLEAR_BIT(RCC_CFGR, PLLMUL_0);
			break; // PLL MUL FACTOR *8
		case 9:
			CLEAR_BIT(RCC_CFGR, PLLMUL_3);
			SET_BIT(RCC_CFGR, PLLMUL_2);
			SET_BIT(RCC_CFGR, PLLMUL_1);
			SET_BIT(RCC_CFGR, PLLMUL_0);
			break; // PLL MUL FACTOR *9
		case 10:
			SET_BIT(RCC_CFGR, PLLMUL_3);
			CLEAR_BIT(RCC_CFGR, PLLMUL_2);
			CLEAR_BIT(RCC_CFGR, PLLMUL_1);
			CLEAR_BIT(RCC_CFGR, PLLMUL_0);
			break; // PLL MUL FACTOR *10
		case 11:
			SET_BIT(RCC_CFGR, PLLMUL_3);
			CLEAR_BIT(RCC_CFGR, PLLMUL_2);
			CLEAR_BIT(RCC_CFGR, PLLMUL_1);
			SET_BIT(RCC_CFGR, PLLMUL_0);
			break; // PLL MUL FACTOR *11
		case 12:
			SET_BIT(RCC_CFGR, PLLMUL_3);
			CLEAR_BIT(RCC_CFGR, PLLMUL_2);
			SET_BIT(RCC_CFGR, PLLMUL_1);
			CLEAR_BIT(RCC_CFGR, PLLMUL_0);
			break; // PLL MUL FACTOR *12
		case 13:
			SET_BIT(RCC_CFGR, PLLMUL_3);
			CLEAR_BIT(RCC_CFGR, PLLMUL_2);
			SET_BIT(RCC_CFGR, PLLMUL_1);
			SET_BIT(RCC_CFGR, PLLMUL_0);
			break; // PLL MUL FACTOR *13
		case 14:
			SET_BIT(RCC_CFGR, PLLMUL_3);
			SET_BIT(RCC_CFGR, PLLMUL_2);
			CLEAR_BIT(RCC_CFGR, PLLMUL_1);
			CLEAR_BIT(RCC_CFGR, PLLMUL_0);
			break; // PLL MUL FACTOR *14
		case 15:
			SET_BIT(RCC_CFGR, PLLMUL_3);
			SET_BIT(RCC_CFGR, PLLMUL_2);
			CLEAR_BIT(RCC_CFGR, PLLMUL_1);
			SET_BIT(RCC_CFGR, PLLMUL_0);
			break; // PLL MUL FACTOR *15
		case 16:
			SET_BIT(RCC_CFGR, PLLMUL_3);
			SET_BIT(RCC_CFGR, PLLMUL_2);
			SET_BIT(RCC_CFGR, PLLMUL_1);
			CLEAR_BIT(RCC_CFGR, PLLMUL_0);
			break; // PLL MUL FACTOR *16

		default:
			CLEAR_BIT(RCC_CFGR, PLLMUL_3);
			CLEAR_BIT(RCC_CFGR, PLLMUL_2);
			CLEAR_BIT(RCC_CFGR, PLLMUL_1);
			CLEAR_BIT(RCC_CFGR, PLLMUL_0);
			break; // PLL MUL FACTOR *2
		}
		/*PLL ON*/
		SET_BIT(RCC_CR, PLLON);
		break;
		/*HSE CLK SOURCE*/
	case HSE:
		switch (HSE_SRC)
		{
		case CRYSTAL:
			CLEAR_BIT(RCC_CR, HSEBYP);
			break; // CRYSTAL IS HSE SOURCE
		case RC:
			SET_BIT(RCC_CR, HSEBYP);
			break; // EXTERNAL RC IS HSE SOURCE
		default:
			CLEAR_BIT(RCC_CR, HSEBYP);
			break;
		}
		/*SELECT HSE AS SYSTEM CLK*/
		SET_BIT(RCC_CFGR, SW_0);
		CLEAR_BIT(RCC_CFGR, SW_1);
		SET_BIT(RCC_CR, HSEON); // HSE ON
		break;
	/*HSI CLK SOURCE*/
	case HSI:
		/*SELECT HSI AS SYSTEM CLK*/
		CLEAR_BIT(RCC_CFGR, SW_0);
		CLEAR_BIT(RCC_CFGR, SW_1);
		SET_BIT(RCC_CR, HSION); // HSI ON
		break;
		/*DEFAULT CLK SRC*/
	default:
		/*SELECT HSI AS SYSTEM CLK*/
		CLEAR_BIT(RCC_CFGR, SW_0);
		CLEAR_BIT(RCC_CFGR, SW_1);
		SET_BIT(RCC_CR, HSION); // HSI ON
		break;
	}

	/*AHB PRESCALER*/
	switch (AHB_PRE)
	{
	case 1:
		CLEAR_BIT(RCC_CFGR, HPRE_3);
		CLEAR_BIT(RCC_CFGR, HPRE_2);
		CLEAR_BIT(RCC_CFGR, HPRE_1);
		CLEAR_BIT(RCC_CFGR, HPRE_0);
		break;
	case 2:
		SET_BIT(RCC_CFGR, HPRE_3);
		CLEAR_BIT(RCC_CFGR, HPRE_2);
		CLEAR_BIT(RCC_CFGR, HPRE_1);
		CLEAR_BIT(RCC_CFGR, HPRE_0);
		break;
	case 4:
		SET_BIT(RCC_CFGR, HPRE_3);
		CLEAR_BIT(RCC_CFGR, HPRE_2);
		CLEAR_BIT(RCC_CFGR, HPRE_1);
		SET_BIT(RCC_CFGR, HPRE_0);
		break;
	case 8:
		SET_BIT(RCC_CFGR, HPRE_3);
		CLEAR_BIT(RCC_CFGR, HPRE_2);
		SET_BIT(RCC_CFGR, HPRE_1);
		CLEAR_BIT(RCC_CFGR, HPRE_0);
		break;
	case 16:
		SET_BIT(RCC_CFGR, HPRE_3);
		CLEAR_BIT(RCC_CFGR, HPRE_2);
		SET_BIT(RCC_CFGR, HPRE_1);
		SET_BIT(RCC_CFGR, HPRE_0);
		break;
	case 64:
		SET_BIT(RCC_CFGR, HPRE_3);
		SET_BIT(RCC_CFGR, HPRE_2);
		CLEAR_BIT(RCC_CFGR, HPRE_1);
		CLEAR_BIT(RCC_CFGR, HPRE_0);
		break;
	case 128:
		SET_BIT(RCC_CFGR, HPRE_3);
		SET_BIT(RCC_CFGR, HPRE_2);
		CLEAR_BIT(RCC_CFGR, HPRE_1);
		SET_BIT(RCC_CFGR, HPRE_0);
		break;
	case 256:
		SET_BIT(RCC_CFGR, HPRE_3);
		SET_BIT(RCC_CFGR, HPRE_2);
		SET_BIT(RCC_CFGR, HPRE_1);
		CLEAR_BIT(RCC_CFGR, HPRE_0);
		break;
	case 512:
		SET_BIT(RCC_CFGR, HPRE_3);
		SET_BIT(RCC_CFGR, HPRE_2);
		SET_BIT(RCC_CFGR, HPRE_1);
		SET_BIT(RCC_CFGR, HPRE_0);
		break;

	default:
		CLEAR_BIT(RCC_CFGR, HPRE_3);
		CLEAR_BIT(RCC_CFGR, HPRE_2);
		CLEAR_BIT(RCC_CFGR, HPRE_1);
		CLEAR_BIT(RCC_CFGR, HPRE_0);
		break;
	}
	/*ABP1 PRESCALER*/
	switch (APB1_PRE)
	{
	case 1:
		CLEAR_BIT(RCC_CFGR, PPRE1_2);
		CLEAR_BIT(RCC_CFGR, PPRE1_1);
		CLEAR_BIT(RCC_CFGR, PPRE1_0);
		break;
	case 2:
		SET_BIT(RCC_CFGR, PPRE1_2);
		CLEAR_BIT(RCC_CFGR, PPRE1_1);
		CLEAR_BIT(RCC_CFGR, PPRE1_0);
		break;
	case 4:
		SET_BIT(RCC_CFGR, PPRE1_2);
		CLEAR_BIT(RCC_CFGR, PPRE1_1);
		SET_BIT(RCC_CFGR, PPRE1_0);
		break;
	case 8:
		SET_BIT(RCC_CFGR, PPRE1_2);
		SET_BIT(RCC_CFGR, PPRE1_1);
		CLEAR_BIT(RCC_CFGR, PPRE1_0);
		break;
	case 16:
		SET_BIT(RCC_CFGR, PPRE1_2);
		SET_BIT(RCC_CFGR, PPRE1_1);
		SET_BIT(RCC_CFGR, PPRE1_0);
		break;

	default:
		CLEAR_BIT(RCC_CFGR, PPRE1_2);
		CLEAR_BIT(RCC_CFGR, PPRE1_1);
		CLEAR_BIT(RCC_CFGR, PPRE1_0);
		break;
	}
	/*ABP2 PRESCALER*/
	switch (APB2_PRE)
	{
	case 1:
		CLEAR_BIT(RCC_CFGR, PPRE2_2);
		CLEAR_BIT(RCC_CFGR, PPRE2_1);
		CLEAR_BIT(RCC_CFGR, PPRE2_0);
		break;
	case 2:
		SET_BIT(RCC_CFGR, PPRE2_2);
		CLEAR_BIT(RCC_CFGR, PPRE2_1);
		CLEAR_BIT(RCC_CFGR, PPRE2_0);
		break;
	case 4:
		SET_BIT(RCC_CFGR, PPRE2_2);
		CLEAR_BIT(RCC_CFGR, PPRE2_1);
		SET_BIT(RCC_CFGR, PPRE2_0);
		break;
	case 8:
		SET_BIT(RCC_CFGR, PPRE2_2);
		SET_BIT(RCC_CFGR, PPRE2_1);
		CLEAR_BIT(RCC_CFGR, PPRE2_0);
		break;
	case 16:
		SET_BIT(RCC_CFGR, PPRE2_2);
		SET_BIT(RCC_CFGR, PPRE2_1);
		SET_BIT(RCC_CFGR, PPRE2_0);
		break;

	default:
		CLEAR_BIT(RCC_CFGR, PPRE2_2);
		CLEAR_BIT(RCC_CFGR, PPRE2_1);
		CLEAR_BIT(RCC_CFGR, PPRE2_0);
		break;
	}
}

void vRCC_EnPerClk(Bus_Name Bus, uint8 Peripheral_Name)
{
	switch (Bus)
	{
	case APB1:
		SET_BIT(RCC_APB1ENR, Peripheral_Name);
		break;
	case APB2:
		SET_BIT(RCC_APB2ENR, Peripheral_Name);
		break;
	default:
		break;
	}
}
